<a href="https://colab.research.google.com/github/2303A51087/B03_PFDS_1087/blob/main/LAB_3_AUG_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np
A=[[3,4],[7,4]]
B=[[13,4],[43,7]]
C=np.array(A)
D=np.array(B)
print("Matrix 1\n",C)
print("Matrix 2\n",D)

Add = np.add(A,B)

print("Addition Result\n",Add)

Sub= np.subtract(A,B)

print("Subtraction Result\n",Sub)

Matrix 1
 [[3 4]
 [7 4]]
Matrix 2
 [[13  4]
 [43  7]]
Addition Result
 [[16  8]
 [50 11]]
Subtraction Result
 [[-10   0]
 [-36  -3]]


In [32]:
import numpy as np
M=[[3,4,5],[7,4,8],[34,6,4]]
N=[[13,4,8],[43,7,1],[23,87,5]]
P=np.array(M)
Q=np.array(N)
print("Matrix 1\n",P)
print("Matrix 2\n",Q)

Add = np.add(M,N)

print("Addition Result\n",Add)

Sub= np.subtract(M,N)

print("Subtraction Result\n",Sub)

Matrix 1
 [[ 3  4  5]
 [ 7  4  8]
 [34  6  4]]
Matrix 2
 [[13  4  8]
 [43  7  1]
 [23 87  5]]
Addition Result
 [[16  8 13]
 [50 11  9]
 [57 93  9]]
Subtraction Result
 [[-10   0  -3]
 [-36  -3   7]
 [ 11 -81  -1]]
